services:
  web:
    env_file:
      - .env
    build:
      context: "./Happy Face"
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
  backend:
    env_file:
      - .env
    build:
      context: "./Smile Base"
      dockerfile: Dockerfile
    ports:
      - ${BE_PORT}:${BE_PORT}
  database:
    env_file:
      - .env
    image: postgres:15.8
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  postgres-data: