site_name: Smile Scheduler Docs

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Mockups: mockups.md
  - Frontend: frontend.md
  - Backend: backend.md
  - Entity Models: entity-models.md
  - Collaboration: collaboration.md