name: CI Workflow

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend - Test, Lint, and Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      working-directory: ./Happy Face
      run: npm ci
      
    - name: Run linting
      working-directory: ./Happy Face
      run: npm run lint
      
    - name: Run tests
      working-directory: ./Happy Face
      run: npm test
      
    - name: Build frontend
      working-directory: ./Happy Face
      run: npm run build

  backend:
    name: Backend - Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        
    - name: Run tests
      working-directory: ./Smile Base
      run: ./gradlew test
      
    - name: Build backend
      working-directory: ./Smile Base
      run: ./gradlew build -x test
